### PR TITLE
Upgrade 0.23, re-organise external examples and tests as external

### PR DESCRIPTION
**Pull request by pinkforest**
- Add self-contained deterministic validation to validate integration as CryptoProvider

### CODE REVIEW

**Comment by pinkforest** [comment]
Moved all the examples as separate crates as well so the dependencies are not polluting the provider crate

**Comment by tarcieri** [comment]
Can you leave the `rustls-rustcrypto` crate in the toplevel (and exclude the others from its crate files in Cargo.tom)? It's the only actual crate of relevance in this repo.

**Comment by pinkforest** [comment]
It gets really difficult to keep clean and there are relevant crates that need to be kept in lock-step
e.g. see self-tester https://github.com/yaws-rs/rustls-rustcrypto/tree/main/self-validate

I also have bunch of other crates that are validation related and need to be kept at workspace.

They have different dependencies thus workspace is easiest but yet need to be kept in lock-step

**Comment by tarcieri** [comment]
It's fine to use a workspace, I'm just saying the `rustls-rustcrypto` crate should be kept in the root directory of the repository, and the other "helper crates" can be put in subdirectories (and excluded from the files in `rustls-rustcrypto` crate releases)

**Comment by pinkforest** [comment]
On other hand it would be nice to solve the API lock-step maintenance issue
- #33 

How about we have "API-crate" for 0.23, 0.22 that proxies to logic-crate given relevant API compats ?

**Comment by tarcieri** [comment]
I'd prefer not to overcomplicate things. I think we only need one crate as a release artifact (`rustls-rustcrypto`) and we should be targeting `rustls` v0.23.

v0.22 is obsolete and we don't need to support that.

**Comment by pinkforest** [comment]
rustls is having accelerated velocity / releases and backporting may become relevant

0.23. - 15 days ago
0.22 - 2 months ago
0.21 - 1 year ago
0.20 - 2 years ago
0.19 - 3 years ago

**Comment by tarcieri** [comment]
`rustls-rustcrypto` hasn't even seen an initial release yet. I don't think we're at the point we need to worry about maintaining extended support for old rustls versions. Let's get an initial release of the crate out first.

**Comment by newpavlov** [comment]
I agree that we should keep the old structure with workspace on top of it, e.g. `rand` [uses](https://github.com/rust-random/rand/blob/master/Cargo.toml#L59-L65) a similar project structure. As for extended support of old versions, in general we do not do it outside of very serious bugs/vulnerabilities. IIUC `rustls` itself does not have any extended support for old versions.

**Comment by tarcieri** [comment]
You need to enable the `rand_core/getrandom` feature for `OsRng`

**Comment by pinkforest** [comment]
Ah thanks! Looks like I was editing wrong file and wondering why it didn't enable it :sweat_smile: 

Added an issue to chase the final bit for `no_std` requiring API here
- #41

**Comment by tarcieri** [comment]
Would it be possible to split this into two PRs: one that reorganizes the tests, and another that does the v0.23 upgrade?

That would be nice to keep the repository history clear/organized.

**Review by tarcieri — APPROVED** [review]

**Comment by stevefan1999-personal** [comment]
External tests doesn't seems to be running in the pipeline

**Comment by pinkforest** [comment]
that is intended because they are not in lockstep with rustls we need to follow - I'm working some self-contained minimal tests atm

**Pull request merged**
