### PR TITLE
CI: run tests

### PR DESCRIPTION
**Pull request by tarcieri**
cc @stevefan1999-personal

### CODE REVIEW

**Comment by stevefan1999-personal** [comment]
my two cents: doc workflow should be on done together with a new release workflow, which is triggered when we publish a new git tag (and also push to crates.io altogether)

We can either create the tag ourselves, or we can use the Github's release button to make a tag for us too,

**Comment by tarcieri** [comment]
We generally run the doc workflow in-band with other tests, where the tests will usually take the longest. Docs are surprisingly easy to break, so it's nice to catch those breakages as part of a PR that's breaking them, instead of a surprise that blocks a release.

**Comment by stevefan1999-personal** [comment]
> We generally run the doc workflow in-band with other tests, where the tests will usually take the longest. Docs are surprisingly easy to break, so it's nice to catch those breakages as part of a PR that's breaking them, instead of a surprise that blocks a release.

Nice catch! However it will definite make the pipeline longer, if the document generation is long. I'm not sure if we would went into a situation where all other stuff are finished but document generation took 5 minutes...Although at this point indeed it seems like something is going on

**Comment by tarcieri** [comment]
It's currently 1m 12s so I'm not too worried.

The tests take 47s, so aside from runner starvation it would save us ~25s.

**Pull request merged**
