### PR TITLE
Validate bare protocol locally against OpenSSL reference

### PR DESCRIPTION
**Pull request by pinkforest**
Should this be re-organised ? e.g. into validation directory ? 

generating the certificates requires openssl binaries in the system so best to just use one year certs ?

### CODE REVIEW

**Comment by tarcieri** [comment]
> generating the certificates requires openssl binaries

You could use the `x509-cert` crate instead.

Shelling out to `openssl` also seems preferable to the certs breaking after a year.

**Comment by pinkforest** [comment]
keen to get rid of those files - x509-cert sounds like ideal

**Comment by pinkforest** [comment]
I moved it under `validation/local_ping_pong_openssl`

I left TODO item into build script so I can later translate the Commands to library calls - just takes a lot of time

**Comment by pinkforest** [comment]
I also added different cipher suites and groups so it tests autoneg & pinned as below:

```
test test::vs_openssl_as_client_ccm8_sha256 - should panic ... ok
test test::vs_openssl_as_client_ccm_sha256 - should panic ... ok
test test::vs_openssl_as_client_group_none - should panic ... ok
test test::vs_openssl_as_client_none - should panic ... ok
test test::vs_openssl_as_client_group_p256 ... ok
test test::vs_openssl_as_client_group_x25519 ... ok
test test::vs_openssl_as_client_poly1305_sha256 ... ok
test test::vs_openssl_as_client_autoneg ... ok
test test::vs_openssl_as_client_gcm_sha256 ... ok
test test::vs_openssl_as_client_gcm_sha384 ... ok
test test::vs_openssl_as_client_group_p384 ... ok
```

**Review by tarcieri — APPROVED** [review]

**Pull request merged**
